# Generated by Django 3.2.13 on 2022-06-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address1', models.CharField(max_length=225)),
                ('address2', models.CharField(max_length=225)),
                ('address3', models.CharField(max_length=225)),
                ('address4', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=225)),
                ('telephone', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('fax', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=225)),
                ('fin_begin', models.DateField()),
                ('books_begin', models.DateField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.countries')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.states')),
            ],
        ),
    ]
