# Generated by Django 3.2.13 on 2022-08-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='states',
            new_name='state',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
