# Generated by Django 3.2.13 on 2022-08-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0002_auto_20220811_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='c_symbol',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='f_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
