# Generated by Django 3.2.13 on 2022-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0003_auto_20220619_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='mailing_name',
            field=models.CharField(default='SOME STRING', max_length=225),
        ),
    ]
