# Generated by Django 3.2.13 on 2022-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_companies_mailing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='currency_symbol',
            field=models.CharField(default='SOME STRING', max_length=225),
        ),
        migrations.AddField(
            model_name='companies',
            name='formal_name',
            field=models.CharField(default='SOME STRING', max_length=225),
        ),
    ]
