# Generated by Django 3.2.13 on 2022-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_rateofexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nature_of_group',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
