# Generated by Django 3.2.13 on 2022-08-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0005_group_nature_of_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='country',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='state',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
