# Generated by Django 3.2.13 on 2022-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0005_auto_20220620_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225, null=True)),
                ('under', models.CharField(max_length=225)),
                ('gp_behaves_like_sub_ledger', models.BooleanField(default=False)),
                ('nett_debit_credit_bal_reporting', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('method_to_allocate_usd_purchase', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companies',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='formal_name',
        ),
        migrations.AddField(
            model_name='countries',
            name='currency_symbol',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='countries',
            name='formal_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='companies',
            name='mailing_name',
            field=models.CharField(max_length=225),
        ),
    ]
