# Generated by Django 3.2.13 on 2022-06-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0006_auto_20220622_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupModel',
        ),
    ]
