# Generated by Django 3.2.13 on 2022-08-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0006_auto_20220820_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='state',
            new_name='states',
        ),
    ]
