# Generated by Django 3.2.13 on 2022-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0007_rename_state_companies_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gross_profit',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
