# Generated by Django 3.2.13 on 2022-06-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0007_delete_groupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225, null=True)),
                ('under', models.CharField(max_length=225)),
                ('sub_ledger', models.BooleanField(default=False)),
                ('debit_credit', models.BooleanField(default=False)),
                ('calculation', models.BooleanField(default=False)),
                ('used_purchase', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
