# Generated by Django 3.2.13 on 2022-08-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0008_group_gross_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='address4',
        ),
    ]
