# Generated by Django 3.2.13 on 2022-07-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0009_auto_20220708_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='bill_wise_entry',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='features',
            name='cost_centres',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='features',
            name='interest_calc',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='features',
            name='maintain_accounts',
            field=models.CharField(max_length=22),
        ),
    ]
