# Generated by Django 3.2.13 on 2022-06-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0009_group_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_accounts', models.BooleanField(default=False)),
                ('bill_wise_entry', models.BooleanField(default=False)),
                ('cost_centres', models.BooleanField(default=False)),
                ('interest_calc', models.BooleanField(default=False)),
                ('maintain_inventory', models.BooleanField(default=False)),
                ('integrate_accounts', models.BooleanField(default=False)),
                ('multiple_price_level', models.BooleanField(default=False)),
                ('batches', models.BooleanField(default=False)),
                ('expirydate_batches', models.BooleanField(default=False)),
                ('joborder_processing', models.BooleanField(default=False)),
                ('cost_tracking', models.BooleanField(default=False)),
                ('job_costing', models.BooleanField(default=False)),
                ('discount_invoices', models.BooleanField(default=False)),
                ('Billed_Quantity', models.BooleanField(default=False)),
                ('sub_ledger', models.BooleanField(default=False)),
                ('gst', models.BooleanField(default=False)),
                ('tds', models.BooleanField(default=False)),
                ('tcs', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=False)),
                ('excise', models.BooleanField(default=False)),
                ('servicetax', models.BooleanField(default=False)),
                ('payroll', models.BooleanField(default=False)),
                ('multiple_addrss', models.BooleanField(default=False)),
                ('vouchers', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
    ]
