# Generated by Django 3.2.13 on 2022-08-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0010_auto_20220822_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost_centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=225)),
                ('cost_alias', models.CharField(max_length=225, null=True)),
                ('under', models.CharField(max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='currencyAlteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=225)),
                ('FormalName', models.CharField(max_length=225)),
                ('ISOCurrency', models.CharField(max_length=225)),
                ('DecimalPlace', models.CharField(max_length=225)),
                ('showAmount', models.BooleanField(default=False)),
                ('suffixSymbol', models.BooleanField(default=False)),
                ('AddSpace', models.BooleanField(default=False)),
                ('wordRep', models.CharField(max_length=225)),
                ('DecimalWords', models.CharField(max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='tally_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=225)),
                ('group_alias', models.CharField(max_length=225, null=True)),
                ('group_under', models.CharField(max_length=225)),
                ('sub_ledger', models.BooleanField(default=False)),
                ('debit_credit', models.BooleanField(default=False)),
                ('calculation', models.BooleanField(default=False)),
                ('invoice', models.CharField(blank=True, max_length=225, null=True)),
                ('nature', models.CharField(blank=True, max_length=225, null=True)),
                ('gross_profit', models.CharField(blank=True, max_length=225, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='company',
        ),
        migrations.RemoveField(
            model_name='group',
            name='company',
        ),
        migrations.RemoveField(
            model_name='gst_details',
            name='company',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='active_this_voucher_type',
            new_name='voucherActivate',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='method_voucher_numbering',
            new_name='voucherNumber',
        ),
        migrations.RemoveField(
            model_name='features',
            name='sub_ledger',
        ),
        migrations.RemoveField(
            model_name='rateofexchange',
            name='currency',
        ),
        migrations.AddField(
            model_name='rateofexchange',
            name='date_ROE',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Costcentre',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Gst_Details',
        ),
        migrations.AddField(
            model_name='rateofexchange',
            name='currencyAlteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.currencyalteration'),
        ),
    ]
