# Generated by Django 3.2.13 on 2022-07-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0010_auto_20220714_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='bill_wise_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='cost_centres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='interest_calc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='maintain_accounts',
            field=models.BooleanField(default=True),
        ),
    ]
