# Generated by Django 3.2.13 on 2022-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0010_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_accounts', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='features',
            name='Billed_Quantity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='batches',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='bill_wise_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='cost_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='discount_invoices',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='excise',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='expirydate_batches',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='integrate_accounts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='interest_calc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='job_costing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='joborder_processing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='maintain_accounts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='maintain_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='multiple_addrss',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='multiple_price_level',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='servicetax',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='sub_ledger',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='vouchers',
            field=models.BooleanField(default=True),
        ),
    ]
