# Generated by Django 3.2.13 on 2022-06-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0011_auto_20220626_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies'),
        ),
    ]
