# Generated by Django 3.2.13 on 2022-08-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0011_auto_20220822_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='use_adv_conf',
            new_name='advance_con',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='prvnt_duplictes',
            new_name='preventDuplicate',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='allow_naration_in_voucher',
            new_name='provideNarration',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='allow_zero_value_trns',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='use_effective_date',
            new_name='voucherEffective',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='provide_naration',
            new_name='voucherNarration',
        ),
    ]
