# Generated by Django 3.2.13 on 2022-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0012_auto_20220822_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateofexchange',
            name='currencyName',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
