# Generated by Django 3.2.13 on 2022-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0012_demo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='bill_wise_entry',
            field=models.BooleanField(default=True),
        ),
    ]
