# Generated by Django 3.2.13 on 2022-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0013_gst_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='country',
            field=models.CharField(default=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='companies',
            name='state',
            field=models.CharField(default=True, max_length=225),
        ),
    ]
