# Generated by Django 3.2.13 on 2022-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0014_auto_20220626_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='disabled',
            field=models.BooleanField(null=True),
        ),
    ]
