# Generated by Django 3.2.13 on 2022-08-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0014_auto_20220824_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gst_lutbond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lutbond', models.CharField(max_length=50)),
                ('validity_from', models.DateField()),
                ('validity_to', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='features',
            name='advance_receipts',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='app_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='applicable_form',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='applicable_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='assessee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='billfrom_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='bond_details',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='dperiod',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='e_invoice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='eway_bill',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='flood_cess',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='gst_applicable',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='gst_classification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='gst_rate_details',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='gstin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='intrastate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='periodicity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='print_eway',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='reg_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='reverse_charge',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='send_ewaybill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='tax_calc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='tax_purchase',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='tax_rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='threshold_includes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='threshold_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='threshold_limit2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies'),
        ),
        migrations.CreateModel(
            name='tds_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('son_daughter', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('pan', models.CharField(max_length=255, null=True)),
                ('flat_no', models.CharField(max_length=10, null=True)),
                ('building', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('std', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Tds_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan_regno', models.CharField(max_length=40)),
                ('tan', models.CharField(max_length=40)),
                ('deductor_type', models.CharField(max_length=100)),
                ('deductor_branch', models.CharField(max_length=255)),
                ('person_details', models.CharField(max_length=255)),
                ('ignore_it', models.CharField(max_length=40)),
                ('active_tds', models.CharField(max_length=40)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='gst_taxability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxability', models.CharField(max_length=50)),
                ('applicable_dt', models.CharField(max_length=50, null=True)),
                ('integrated_tax', models.CharField(max_length=50)),
                ('cess', models.CharField(max_length=50)),
                ('flood_cess', models.CharField(max_length=50)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
    ]
