# Generated by Django 3.2.13 on 2022-06-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0015_companies_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
