# Generated by Django 3.2.13 on 2023-04-26 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0015_auto_20220824_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='advance_receipts',
        ),
        migrations.RemoveField(
            model_name='features',
            name='app_from',
        ),
        migrations.RemoveField(
            model_name='features',
            name='applicable_form',
        ),
        migrations.RemoveField(
            model_name='features',
            name='applicable_from',
        ),
        migrations.RemoveField(
            model_name='features',
            name='assessee',
        ),
        migrations.RemoveField(
            model_name='features',
            name='billfrom_place',
        ),
        migrations.RemoveField(
            model_name='features',
            name='bond_details',
        ),
        migrations.RemoveField(
            model_name='features',
            name='dperiod',
        ),
        migrations.RemoveField(
            model_name='features',
            name='e_invoice',
        ),
        migrations.RemoveField(
            model_name='features',
            name='eway_bill',
        ),
        migrations.RemoveField(
            model_name='features',
            name='flood_cess',
        ),
        migrations.RemoveField(
            model_name='features',
            name='gst_applicable',
        ),
        migrations.RemoveField(
            model_name='features',
            name='gst_classification',
        ),
        migrations.RemoveField(
            model_name='features',
            name='gst_rate_details',
        ),
        migrations.RemoveField(
            model_name='features',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='features',
            name='intrastate',
        ),
        migrations.RemoveField(
            model_name='features',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='features',
            name='print_eway',
        ),
        migrations.RemoveField(
            model_name='features',
            name='reg_type',
        ),
        migrations.RemoveField(
            model_name='features',
            name='reverse_charge',
        ),
        migrations.RemoveField(
            model_name='features',
            name='send_ewaybill',
        ),
        migrations.RemoveField(
            model_name='features',
            name='tax_calc',
        ),
        migrations.RemoveField(
            model_name='features',
            name='tax_purchase',
        ),
        migrations.RemoveField(
            model_name='features',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='features',
            name='threshold_includes',
        ),
        migrations.RemoveField(
            model_name='features',
            name='threshold_limit',
        ),
        migrations.RemoveField(
            model_name='features',
            name='threshold_limit2',
        ),
        migrations.AddField(
            model_name='gst',
            name='advance_receipts',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='app_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='applicable_form',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='applicable_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='assessee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='billfrom_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='bond_details',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies'),
        ),
        migrations.AddField(
            model_name='gst',
            name='dperiod',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='e_invoice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='eway_bill',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='flood_cess',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='gst_applicable',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='gst_classification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='gst_rate_details',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='gstin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='intrastate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='periodicity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='print_eway',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='reg_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='reverse_charge',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='send_ewaybill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='tax_calc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='tax_purchase',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='tax_rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='threshold_includes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='threshold_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gst',
            name='threshold_limit2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies'),
        ),
    ]
