# Generated by Django 3.2.13 on 2022-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0017_alter_companies_disabled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demo',
            new_name='feature',
        ),
    ]
