# Generated by Django 3.2.13 on 2022-06-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0018_rename_demo_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feature',
        ),
    ]
