# Generated by Django 3.2.13 on 2022-06-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0019_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nature_of_group',
            field=models.CharField(default='data', max_length=225),
        ),
    ]
