# Generated by Django 3.2.13 on 2022-06-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0021_alter_group_nature_of_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='company',
        ),
        migrations.RemoveField(
            model_name='group',
            name='company',
        ),
        migrations.AlterField(
            model_name='countries',
            name='currency_symbol',
            field=models.CharField(default='र', max_length=225),
        ),
        migrations.AlterField(
            model_name='countries',
            name='formal_name',
            field=models.CharField(default='INR', max_length=225),
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='features',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
