# Generated by Django 3.2.13 on 2022-06-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0022_auto_20220629_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpname', models.CharField(max_length=225)),
                ('mailing_name', models.CharField(max_length=225)),
                ('address1', models.CharField(max_length=225)),
                ('address2', models.CharField(max_length=225)),
                ('address3', models.CharField(max_length=225)),
                ('address4', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=6)),
                ('telephone', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('fax', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=225)),
                ('fin_begin', models.DateField(null=True)),
                ('books_begin', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.countries')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.states')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpname', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225, null=True)),
                ('under', models.CharField(max_length=225)),
                ('sub_ledger', models.BooleanField(default=False)),
                ('debit_credit', models.BooleanField(default=False)),
                ('calculation', models.BooleanField(default=False)),
                ('used_purchase', models.CharField(blank=True, max_length=225, null=True)),
                ('nature_of_group', models.CharField(max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_accounts', models.BooleanField(default=True)),
                ('bill_wise_entry', models.BooleanField(default=True)),
                ('cost_centres', models.BooleanField(default=False)),
                ('interest_calc', models.BooleanField(default=True)),
                ('maintain_inventory', models.BooleanField(default=True)),
                ('integrate_accounts', models.BooleanField(default=True)),
                ('multiple_price_level', models.BooleanField(default=True)),
                ('batches', models.BooleanField(default=True)),
                ('expirydate_batches', models.BooleanField(default=True)),
                ('joborder_processing', models.BooleanField(default=True)),
                ('sub_ledger', models.BooleanField(default=True)),
                ('cost_tracking', models.BooleanField(default=True)),
                ('job_costing', models.BooleanField(default=True)),
                ('discount_invoices', models.BooleanField(default=True)),
                ('Billed_Quantity', models.BooleanField(default=True)),
                ('gst', models.BooleanField(default=False)),
                ('tds', models.BooleanField(default=False)),
                ('tcs', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=False)),
                ('excise', models.BooleanField(default=True)),
                ('servicetax', models.BooleanField(default=True)),
                ('payroll', models.BooleanField(default=False)),
                ('multiple_addrss', models.BooleanField(default=True)),
                ('vouchers', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
    ]
