# Generated by Django 3.2.13 on 2022-06-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0023_companies_features_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='cmpname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='grpname',
            new_name='name',
        ),
    ]
