# Generated by Django 3.2.13 on 2022-07-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0025_costcentre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=225)),
                ('formal_name', models.CharField(max_length=225)),
                ('currency_code', models.CharField(max_length=225)),
                ('decimal_places', models.CharField(max_length=225)),
                ('show_in_millions', models.BooleanField(default=False)),
                ('suffix_symbol', models.BooleanField(default=False)),
                ('symbol_and_amount', models.BooleanField(default=False)),
                ('after_decimal', models.CharField(max_length=225)),
                ('amount_in_words', models.CharField(max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
    ]
